/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FlashcardSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  baseUrl: "http://192.168.3.11:8887",
  username: "",
  password: "",
  autoSync: true,
  syncDelayMs: 3e3
};

// src/api.ts
var import_obsidian = require("obsidian");
var FlashcardAPI = class {
  constructor(baseUrl) {
    this.token = null;
    this.baseUrl = baseUrl.replace(/\/$/, "");
  }
  async login(username, password) {
    const res = await (0, import_obsidian.requestUrl)({
      url: `${this.baseUrl}/api/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ username, password })
    });
    const data = res.json;
    if (data.access_token) {
      this.token = data.access_token;
    } else {
      throw new Error(data.message || "Login failed");
    }
  }
  async pushNote(title, content, sourcePath) {
    if (!this.token) {
      throw new Error("Not authenticated");
    }
    const res = await (0, import_obsidian.requestUrl)({
      url: `${this.baseUrl}/api/notes/push`,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.token}`
      },
      body: JSON.stringify({ title, content, source_path: sourcePath })
    });
    if (res.status !== 200) {
      const data = res.json;
      throw new Error(data.message || `Push failed (${res.status})`);
    }
  }
  isAuthenticated() {
    return this.token !== null;
  }
};

// src/main.ts
var FlashcardSyncPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.syncTimer = null;
    this.modifiedFiles = /* @__PURE__ */ new Set();
  }
  async onload() {
    await this.loadSettings();
    this.api = new FlashcardAPI(this.settings.baseUrl);
    this.addSettingTab(new FlashcardSettingTab(this.app, this));
    this.statusBarEl = this.addStatusBarItem();
    this.statusBarEl.setText("\u95EA\u5361: \u672A\u767B\u5F55");
    this.addRibbonIcon("upload", "\u63A8\u9001\u5F53\u524D\u7B14\u8BB0\u5230\u95EA\u5361\u7CFB\u7EDF", () => {
      this.pushCurrentNote();
    });
    this.addCommand({
      id: "push-current-note",
      name: "\u63A8\u9001\u5F53\u524D\u7B14\u8BB0\u5230\u95EA\u5361\u7CFB\u7EDF",
      callback: () => this.pushCurrentNote()
    });
    this.addCommand({
      id: "login-to-flashcard",
      name: "\u767B\u5F55\u95EA\u5361\u7CFB\u7EDF",
      callback: () => this.login()
    });
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (!this.settings.autoSync) return;
        if (file instanceof import_obsidian2.TFile && file.extension === "md") {
          this.modifiedFiles.add(file.path);
          this.debounceSync();
        }
      })
    );
    if (this.settings.username && this.settings.password) {
      this.login().catch(() => {
        this.updateStatus("\u767B\u5F55\u5931\u8D25");
      });
    }
  }
  onunload() {
    if (this.syncTimer !== null) {
      window.clearTimeout(this.syncTimer);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async login() {
    try {
      this.api = new FlashcardAPI(this.settings.baseUrl);
      await this.api.login(this.settings.username, this.settings.password);
      this.updateStatus("\u5DF2\u767B\u5F55");
      new import_obsidian2.Notice("\u95EA\u5361\u7CFB\u7EDF\u767B\u5F55\u6210\u529F");
    } catch (e) {
      this.updateStatus("\u767B\u5F55\u5931\u8D25");
      new import_obsidian2.Notice(`\u767B\u5F55\u5931\u8D25: ${e.message}`);
      throw e;
    }
  }
  async pushCurrentNote() {
    const file = this.app.workspace.getActiveFile();
    if (!file || file.extension !== "md") {
      new import_obsidian2.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u7B14\u8BB0");
      return;
    }
    await this.pushFile(file);
  }
  async pushFile(file) {
    if (!this.api.isAuthenticated()) {
      try {
        await this.login();
      } catch (e) {
        new import_obsidian2.Notice("\u8BF7\u5148\u914D\u7F6E\u8D26\u53F7\u5BC6\u7801\u5E76\u767B\u5F55");
        return;
      }
    }
    try {
      this.updateStatus("\u63A8\u9001\u4E2D...");
      const content = await this.app.vault.read(file);
      await this.api.pushNote(file.basename, content, file.path);
      this.updateStatus("\u63A8\u9001\u6210\u529F");
      new import_obsidian2.Notice(`\u5DF2\u63A8\u9001: ${file.basename}`);
    } catch (e) {
      this.updateStatus("\u63A8\u9001\u5931\u8D25");
      new import_obsidian2.Notice(`\u63A8\u9001\u5931\u8D25: ${e.message}`);
    }
  }
  debounceSync() {
    if (!this.settings.autoSync) return;
    if (this.syncTimer !== null) {
      window.clearTimeout(this.syncTimer);
    }
    this.syncTimer = window.setTimeout(() => {
      this.syncModifiedFiles();
    }, this.settings.syncDelayMs);
  }
  async syncModifiedFiles() {
    if (!this.settings.autoSync) return;
    if (!this.api.isAuthenticated()) return;
    for (const path of Array.from(this.modifiedFiles)) {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian2.TFile) {
        try {
          await this.pushFile(file);
        } catch (e) {
        }
      }
    }
    this.modifiedFiles.clear();
  }
  updateStatus(text) {
    this.statusBarEl.setText(`\u95EA\u5361: ${text}`);
  }
};
var FlashcardSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u95EA\u5361\u540C\u6B65\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("\u670D\u52A1\u5668\u5730\u5740").setDesc("\u540E\u7AEF API \u5730\u5740").addText(
      (text) => text.setPlaceholder("http://192.168.3.11:8887").setValue(this.plugin.settings.baseUrl).onChange(async (value) => {
        this.plugin.settings.baseUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u7528\u6237\u540D").setDesc("\u95EA\u5361\u7CFB\u7EDF\u7528\u6237\u540D").addText(
      (text) => text.setPlaceholder("username").setValue(this.plugin.settings.username).onChange(async (value) => {
        this.plugin.settings.username = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u5BC6\u7801").setDesc("\u95EA\u5361\u7CFB\u7EDF\u5BC6\u7801").addText(
      (text) => text.setPlaceholder("password").setValue(this.plugin.settings.password).onChange(async (value) => {
        this.plugin.settings.password = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u4FDD\u5B58\u65F6\u81EA\u52A8\u63A8\u9001").setDesc("\u7B14\u8BB0\u4FDD\u5B58\u540E\u81EA\u52A8\u63A8\u9001\u5230\u95EA\u5361\u7CFB\u7EDF").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSync).onChange(async (value) => {
        this.plugin.settings.autoSync = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u63A8\u9001\u5EF6\u8FDF").setDesc("\u4FDD\u5B58\u540E\u5EF6\u8FDF\u591A\u5C11\u6BEB\u79D2\u63A8\u9001\uFF08\u9632\u6296\uFF09").addSlider(
      (slider) => slider.setLimits(1e3, 1e4, 500).setValue(this.plugin.settings.syncDelayMs).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.syncDelayMs = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u6D4B\u8BD5\u767B\u5F55").setDesc("\u9A8C\u8BC1\u8D26\u53F7\u5BC6\u7801\u662F\u5426\u6B63\u786E").addButton(
      (btn) => btn.setButtonText("\u767B\u5F55").onClick(() => this.plugin.login())
    );
  }
};
